### ISSUE TITLE
mremap_encrypted: Cannot allocate memory

### ISSUE THREAD

**Issue by kevindick** [meme/apple-tools#2]
mremap_encrypted fails with "Cannot allocate memory" when testing on M1 mac

Target binary is a universal app, thinned to arm64 with lipo. 
<img width="769" alt="image" src="https://user-images.githubusercontent.com/60417776/112740509-92dc9b00-8f32-11eb-8957-daffe5c5fd8f.png">

<img width="774" alt="image" src="https://user-images.githubusercontent.com/60417776/112740438-e995a500-8f31-11eb-8df3-d96ce8f27176.png">

**Comment by meme** [comment]
Take a look at the context around https://github.com/apple/darwin-xnu/blob/main/bsd/kern/kern_mman.c#L1569, check Console.app log messages and match them up. Specifically the `result` value. Not sure if thinning causes issues.

**Comment by kevindick** [comment]
Thank you for the pointer, got a few leads now. Will do some more research and experimentation with how universal machos are launched and submit a pr if I can get working. Looks like thinning indeeds breaks something, interestingly it also intermittently triggers a kernel panic on launch when subbing the universal binary with the thinned binary in the .app package.
